dubbo:
  application:
    name: user-service-provider  # 服务器的应用
  registry:
    address: 127.0.0.1:2181 # 注册中心地址
    protocol: zookeeper     # 注册中心协议

  protocol:
    port: 20880
    name: dubbo     # 通信规则(通信协议？通信端口)
  monitor:
    protocol: registry   # 监控中心
